
FROM node:14-alpine

WORKDIR /usr/src/app/

RUN apk update && apk add bash

RUN yarn global add expo-cli

# add git command
RUN apk update && \
    npm install && \
    npm install -g npm && \
    npm install -g vue-cli && \
    npm install -g http-server && \
    apk add git

EXPOSE 19000
EXPOSE 19001
EXPOSE 19002
EXPOSE 19006

RUN yarn global add @expo/ngrok@^4.1.0

RUN npm install expo